spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenitydb
    username: root     # ????? ?? ??
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create   # update or create or none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

server:
  port: 8080